main: com.cceckman.blocks.App
description: Enable Linux to use Minecraft chests as block storage devices.
name: popular-block-storage
version: 0.1
api-version: 1.15
load: POSTWORLD
authors: [cceckman, slongfield]
website: https://github.com/cceckman/popular-block-storage

commands:
    mkchest:
        description: Place a chest in the world.