package com.cceckman.blocks;

import java.util.logging.Logger;

import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.event.HandlerList;
import org.bukkit.scheduler.BukkitRunnable;

// Runnable operation of updating or reading from a block storage device.
// Generated by a server thread; closes over a World.
// Per: https://www.spigotmc.org/wiki/using-the-event-api/
public class OffsetOperation extends BukkitRunnable {
    public OffsetOperation(final Logger l, final World w, final long offset, final long length) {
        logger_ = l;
        world_ = w;
        offset_ = offset;
        length_ = length;
    }

    private static final HandlerList HANDLERS = new HandlerList();

    public HandlerList getHandlers() {
        return HANDLERS;
    }

    public static HandlerList getHandlerList() {
        return HANDLERS;
    }

    private final long offset_; // Offset of the request: first address read / written.
    private final long length_; // Length of request: read / written.
    private final World world_;
    private final Logger logger_;

    public long getLength() {
        return length_;
    }

    // Applies this transformation to the world.
    // Must be applied from the main thread!
    public void run() {
        final var coords = new Coordinates(this.offset_);
        final var block = this.world_.getBlockAt(coords.x, coords.y, coords.z);
        block.setType(Material.BRICKS);
        logger_.info(String.format("Turned (%d, %d, %d) into a brick", coords.x, coords.y, coords.z));
    }
}